### ISSUE TITLE
MinimumOSVersion导致ITMS-90208

### ISSUE THREAD

**Issue by icofans** [Ezviz-OpenBiz/SDK-iOS#18]
请修改info.plist文件中的MinimumOSVersion，否则上传商店会提示
ERROR ITMS-90208: "Invalid Bundle. The bundle EZOpenSDKFramework.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by Ezviz-Open** [comment]
已修改，SDK升级至v5.2即可。
