### ISSUE TITLE
Crash on app startup iOS 12.5.7

### ISSUE THREAD

**Issue by mauzis** [Ezviz-OpenBiz/SDK-iOS#20]
App is crashing on startup doesn't even reach 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

Problem exists if using SDK version above 5.5.1 

In case using 5.5.1 app starts without crashing

**Comment by Ezviz-Open** [comment]
Please upgrade to version 5.8.1 or higher
