### ISSUE TITLE
这个可以用git管理工具导入工程吗？？？总是爆失败啊

### ISSUE THREAD

**Issue by GarthGit** [Ezviz-OpenBiz/SDK-iOS#7]

**Comment by GarthGit** [comment]
日志没有，可以去官网看的，关键是官网提示的导入方法不行，常规也不行，只能手动导入
在Podfile文件中添加如下语句
pod 'EZOpenSDK'
执行
pod install
已经可以导入了

**Comment by GarthGit** [comment]
手动导入需要很多配置的，就怕和其他的一些导入的第三方库相互冲突

**Comment by GarthGit** [comment]
1. 使用有限制
2. 没有人维护
这是我看的SDK的状态提示
最好还是能写写commit日志，这样形象更好

**Comment by GarthGit** [comment]
好吧，我导入错误了

**Comment by hasakey** [comment]
cocopods还是导入不了
